language: R
cache: packages
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true

env:
   global:
     - R_BUILD_ARGS="--no-vignettes --no-manual"
     - R_CHECK_ARGS="--no-vignettes --no-manual --as-cran"
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false

warnings_are_errors: false

r_github_packages:
  - mikejohnson51/AOI
  - mikejohnson51/nwm
  
notifications:
  email:
    on_success: change
    on_failure: change